# Generated by Django 5.1.7 on 2025-06-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0002_product_price_product_type_project_supplierlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='product_catalogue.supplierlist'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='product_catalogue.product'),
        ),
        migrations.CreateModel(
            name='SupplierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_attachments/', verbose_name='File')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='product_catalogue.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Supplier Attachment',
                'verbose_name_plural': 'Supplier Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
