# Generated by Django 5.1.7 on 2025-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0003_alter_supplier_list_alter_supplier_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cost Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Used to auto-calculate price from cost', max_digits=5, null=True, verbose_name='Desired Profit Margin (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('farm_use', 'Farm Use Only'), ('resell', 'Resell in Store'), ('produced', 'Produced by Farm')], default='farm_use', max_length=20, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_store',
            field=models.BooleanField(default=False, verbose_name='Visible in Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('unit', 'Unit'), ('bag', 'Bag')], default='kg', max_length=10, verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
