# Generated by Django 5.1.7 on 2025-07-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0006_alter_personalproduct_farm_alter_product_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('animal', 'Animal'), ('agricultural', 'Agricultural'), ('raw_material', 'Raw Material'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
