# Generated by Django 5.1.7 on 2025-07-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0007_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='efficiency_time',
            field=models.PositiveIntegerField(blank=True, help_text='How many days until this agricultural product becomes effective', null=True, verbose_name='Efficiency Time'),
        ),
    ]
