# Generated by Django 5.1.7 on 2025-04-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person'),
        ('product_catalogue', '0002_product_price_product_type_project_supplierlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='product_catalogue.supplier', verbose_name='Linked Supplier'),
        ),
        migrations.AddField(
            model_name='person',
            name='team_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='core.teammember', verbose_name='Linked Team Member'),
        ),
    ]
