# Generated by Django 5.1.7 on 2025-07-10 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the related object.', verbose_name='Object ID')),
                ('name', models.CharField(blank=True, help_text='Readable name for this attachment (optional).', max_length=255, null=True, verbose_name='Attachment Name')),
                ('file', models.FileField(help_text='The attached file.', upload_to='attachments/%Y/%m/%d/', verbose_name='File')),
                ('file_type', models.CharField(blank=True, help_text='Type of the file (image, pdf, etc.).', max_length=50, null=True, verbose_name='File Type')),
                ('extension', models.CharField(blank=True, help_text='File extension, e.g., pdf, jpg.', max_length=10, null=True, verbose_name='File Extension')),
                ('size', models.PositiveBigIntegerField(blank=True, help_text='Size of the file in bytes.', null=True, verbose_name='File Size (bytes)')),
                ('description', models.CharField(blank=True, help_text='Optional description for this attachment.', max_length=255, null=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this attachment is publicly accessible.', verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this attachment was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this attachment was last updated.', verbose_name='Updated At')),
                ('content_type', models.ForeignKey(help_text='Content type of the related object.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this attachment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
