# Generated by Django 5.1.7 on 2025-04-05 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the expense list.', max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optional reference code or number.', max_length=20, null=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('agriculture', 'Agriculture'), ('animal', 'Animal'), ('warehouse', 'Warehouse'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monthly Budget')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='expenses/categories/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Expense Number')),
                ('label', models.CharField(help_text='What the expense is (e.g., salary, service).', max_length=100, verbose_name='Label')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.expensecategory', verbose_name='Category')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Expense Item',
                'verbose_name_plural': 'Expense Items',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, image, or document related to the expense.', upload_to='expenses/attachments/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.expenseitem', verbose_name='Expense Item')),
            ],
            options={
                'verbose_name': 'Expense Attachment',
                'verbose_name_plural': 'Expense Attachments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, verbose_name='Payment Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('accountant_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accountant Signature')),
                ('recipient_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recipient Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('person', models.ForeignKey(help_text='The person receiving the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.person', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Payment Voucher',
                'verbose_name_plural': 'Payment Vouchers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, image, or document related to the payment.', upload_to='payments/attachments/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Attachment',
                'verbose_name_plural': 'Payment Attachments',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Receipt Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('accountant_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accountant Signature')),
                ('recipient_signature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recipient Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('person', models.ForeignKey(help_text='The person making the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.person', verbose_name='Payer')),
            ],
            options={
                'verbose_name': 'Receipt Voucher',
                'verbose_name_plural': 'Receipt Vouchers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, image, or document related to the receipt.', upload_to='receipts/attachments/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.receipt', verbose_name='Receipt')),
            ],
            options={
                'verbose_name': 'Receipt Attachment',
                'verbose_name_plural': 'Receipt Attachments',
            },
        ),
    ]
