# Generated by Django 5.1.7 on 2025-04-06 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_supplier_person_team_member'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(max_length=50, unique=True, verbose_name='Company Number')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Branch Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('internet', 'Internet'), ('other', 'Other')], max_length=20, verbose_name='Service Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(max_length=50, unique=True, verbose_name='Subscription Number')),
                ('name', models.CharField(max_length=255, verbose_name='Subscription Name')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Amount')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='finance.servicecompany', verbose_name='Service Company')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
