# Generated by Django 5.1.7 on 2025-04-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_supplier_person_team_member'),
        ('finance', '0002_servicecompany_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Due'), ('partially_paid', 'Partially Paid'), ('paid', 'Fully Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('person', models.ForeignKey(help_text='Person this debt is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='DebtAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='debts/attachments/', verbose_name='Attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.debt', verbose_name='Debt')),
            ],
            options={
                'verbose_name': 'Debt Attachment',
                'verbose_name_plural': 'Debt Attachments',
            },
        ),
    ]
