# Generated by Django 5.1.7 on 2025-04-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_supplier_person_team_member'),
        ('finance', '0003_debt_debtattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtattachment',
            name='file',
            field=models.FileField(help_text='PDF, image, or document related to the debt.', upload_to='debts/attachments/', verbose_name='Attachment File'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('buyer_number', models.CharField(max_length=50, verbose_name='Buyer Number')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'ordering': ['-created_at'],
            },
        ),
    ]
