# Generated by Django 5.1.7 on 2025-04-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_person_supplier_person_team_member'),
        ('finance', '0005_salesinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Invoice Number')),
                ('product_object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('installment', 'Installment'), ('other', 'Other')], max_length=50, verbose_name='Payment Method')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('product_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('supplier', models.ForeignKey(limit_choices_to={'type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.person', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, image, or document related to the purchase.', upload_to='purchases/attachments/', verbose_name='Attachment File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.purchaseinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Purchase Attachment',
                'verbose_name_plural': 'Purchase Attachments',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.purchaseinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'ordering': ['-date'],
            },
        ),
    ]
