# Generated by Django 5.1.7 on 2025-07-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_purchaseinvoice_supplier'),
        ('product_catalogue', '0006_alter_personalproduct_farm_alter_product_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'supplier_name'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='product_catalogue.supplier', verbose_name='Supplier'),
        ),
    ]
