# Generated by Django 5.1.7 on 2025-07-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
        ('finance', '0010_alter_purchaseinvoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.person', verbose_name='Supplier'),
        ),
    ]
