# Generated by Django 5.1.7 on 2025-07-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
        ('finance', '0011_alter_purchaseinvoice_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_from',
            field=models.TextField(default=1, help_text='Seller details for the invoice header', verbose_name='Invoice From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_to',
            field=models.TextField(default=1, help_text='Buyer details for the invoice header', verbose_name='Invoice To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.salesinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Sales Invoice Item',
                'verbose_name_plural': 'Sales Invoice Items',
            },
        ),
    ]
