# Generated by Django 5.1.7 on 2025-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_salesinvoice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
        ),
    ]
