# Generated by Django 5.1.7 on 2025-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_salesinvoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service'),
        ),
    ]
