# Generated by Django 5.1.7 on 2025-07-05 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
        ('finance', '0014_salesinvoiceitem_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date'], 'verbose_name': 'Purchase Invoice', 'verbose_name_plural': 'Purchase Invoices'},
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='product_content_type',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='product_object_id',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_from',
            field=models.TextField(default='Farm', help_text='Seller details for the invoice header', verbose_name='Invoice From'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_to',
            field=models.TextField(default='Farm', help_text='Buyer details for the invoice header', verbose_name='Invoice To'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='location',
            field=models.CharField(default='turkey', max_length=100, verbose_name='Transaction Location'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit Card'), ('transfer', 'Bank Transfer'), ('installment', 'Installment'), ('other', 'Other')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.person', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('service', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchaseinvoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Purchase Invoice Item',
                'verbose_name_plural': 'Purchase Invoice Items',
            },
        ),
    ]
