# Generated by Django 5.1.7 on 2025-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='type',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('animal', 'Animal'), ('warehouse', 'Warehouse'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type'),
        ),
    ]
