# Generated by Django 5.1.7 on 2025-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_expensecategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product'),
        ),
    ]
