# Generated by Django 5.1.7 on 2025-04-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('land', '0001_initial'),
        ('product_catalogue', '0002_product_price_product_type_project_supplierlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Agricultural Land Code')),
                ('name', models.CharField(max_length=255, verbose_name='Land Name')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_lands', to='land.land', verbose_name='Linked Land')),
            ],
            options={
                'verbose_name': 'Agricultural Land',
                'verbose_name_plural': 'Agricultural Lands',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100, verbose_name='Crop Type')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed'), ('sold', 'Sold')], max_length=20, verbose_name='Crop Status')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('sack', 'Sack')], max_length=10, verbose_name='Unit')),
                ('usage', models.CharField(choices=[('for_sale', 'For Sale'), ('for_feed', 'Animal Feed')], max_length=20, verbose_name='Usage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('agricultural_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crop.agriculturalland', verbose_name='Agricultural Land')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LandStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ploughing', 'Ploughing'), ('softening', 'Softening'), ('planted', 'Planted'), ('unusable', 'Unusable'), ('treatment', 'Treatment'), ('unused', 'Unused')], max_length=30, verbose_name='Land Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Used')),
                ('date', models.DateField(verbose_name='Status Date')),
                ('agricultural_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='crop.agriculturalland', verbose_name='Agricultural Land')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('product_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_catalogue.product', verbose_name='Product Used')),
            ],
            options={
                'verbose_name': 'Land Status',
                'verbose_name_plural': 'Land Statuses',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='agriculturalland',
            index=models.Index(fields=['code', 'farm'], name='crop_agricu_code_8c500c_idx'),
        ),
    ]
