# Generated by Django 5.1.7 on 2025-04-05 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Warehouse Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('space', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Space (m²)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouses/images/', verbose_name='Main Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='warehouses/gallery/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Image Title')),
                ('description', models.TextField(blank=True, verbose_name='Image Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Image',
                'verbose_name_plural': 'Warehouse Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='warehouses/videos/', verbose_name='Video')),
                ('title', models.CharField(max_length=255, verbose_name='Video Title')),
                ('description', models.TextField(blank=True, verbose_name='Video Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Video',
                'verbose_name_plural': 'Warehouse Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
