# Generated by Django 5.1.7 on 2025-04-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Reference ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight')),
                ('space_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Space Taken (m²)')),
                ('date_added', models.DateField(verbose_name='Date Added')),
                ('entry_presence', models.CharField(choices=[('real', 'Real (Physical)'), ('virtual', 'Virtual (Logical)')], default='real', max_length=10, verbose_name='Entry Presence Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Entry Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Entry',
                'verbose_name_plural': 'Warehouse Entries',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseQuantitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=20, verbose_name='Action')),
                ('frequency', models.CharField(max_length=50, verbose_name='Frequency')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_schedules', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Quantity Schedule',
                'verbose_name_plural': 'Warehouse Quantity Schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
