# Generated by Django 5.1.7 on 2025-04-05 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('warehouse', '0002_warehouseentry_warehousequantityschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousequantityschedule',
            name='quantity',
        ),
        migrations.AddField(
            model_name='warehousequantityschedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousequantityschedule',
            name='action',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='warehousequantityschedule',
            name='frequency',
            field=models.CharField(max_length=50, verbose_name='Frequency (e.g. daily, weekly)'),
        ),
        migrations.CreateModel(
            name='WarehouseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('alert_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alert Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Reminder',
                'verbose_name_plural': 'Warehouse Reminders',
                'ordering': ['-created_at'],
            },
        ),
    ]
