# Generated by Django 5.1.7 on 2025-04-05 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_warehousequantityschedule_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseentry',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
    ]
