# Generated by Django 5.1.7 on 2025-04-05 07:57

import warehouse.models.entry
from django.db import migrations, models
from warehouse.models.entry import default_today

class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehouseentry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseentry',
            name='date_added',
            field=models.DateField(default=default_today, verbose_name='Date Added'),

        ),
    ]
