# Generated by Django 5.1.7 on 2025-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_warehouseentry_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseentry',
            name='origin',
            field=models.CharField(choices=[('produced', 'Produced by farm'), ('purchased', 'Purchased externally')], default='purchased', max_length=20, verbose_name='Origin'),
        ),
    ]
