# Generated by Django 5.1.7 on 2025-07-06 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
        ('warehouse', '0007_alter_warehouse_farm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('removed', 'Removed'), ('transferred', 'Transferred')], default='in_stock', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='warehouseentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['name'], name='warehouse_w_name_690490_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouse_w_is_acti_5ddb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseentry',
            index=models.Index(fields=['warehouse', 'content_type', 'object_id'], name='warehouse_w_warehou_694ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseentry',
            index=models.Index(fields=['date_added'], name='warehouse_w_date_ad_966b84_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseentry',
            index=models.Index(fields=['status'], name='warehouse_w_status_61fa92_idx'),
        ),
    ]
