class LogActions:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    SWITCH_FARM = "SWITCH_FARM"

    # 🔁 Birth Transfers
    AUTO_BIRTH_TRANSFER = "AUTO_BIRTH_TRANSFER"
    MANUAL_BIRTH_TRANSFER = "MANUAL_BIRTH_TRANSFER"

    # 🐄 Animal Actions
    ANIMAL_CREATED = "ANIMAL_CREATED"
    ANIMAL_DELETED = "ANIMAL_DELETED"
    ANIMAL_DEATH = "ANIMAL_DEATH"
    VACCINE_ADDED = "VACCINE_ADDED"

    # 💱 Currency
    CURRENCY_RATE_UPDATED = "CURRENCY_RATE_UPDATED"
    CURRENCY_ADDED = "CURRENCY_ADDED"