# Generated by Django 5.1.7 on 2025-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='farm_logos/', verbose_name='Logo'),
        ),
    ]
