# Generated by Django 5.1.7 on 2025-06-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_status'),
        ('farm_settings', '0003_remove_farmsettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('animal', 'Animal'), ('crop', 'Crop'), ('land', 'Land'), ('product', 'Product')], max_length=50)),
                ('image', models.ImageField(upload_to='defaults/', verbose_name='Image')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Default Farm Image',
                'verbose_name_plural': 'Default Farm Images',
                'unique_together': {('farm', 'type')},
            },
        ),
    ]
