# Generated by Django 5.1.7 on 2025-07-10 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
        ('farm_settings', '0005_alter_defaultfarmimage_farm_alter_farmcurrency_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank', max_length=255, verbose_name='Bank Name')),
                ('bank_number', models.CharField(help_text='Internal bank number', max_length=100, unique=True, verbose_name='Bank Number')),
                ('branch', models.CharField(blank=True, help_text='Branch of the bank', max_length=255, null=True, verbose_name='Branch')),
                ('account_number', models.CharField(help_text='Bank account number', max_length=100, unique=True, verbose_name='Account Number')),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, null=True, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, help_text='Bank SWIFT code', max_length=11, null=True, verbose_name='SWIFT Code')),
                ('address', models.CharField(blank=True, help_text='Address of the bank', max_length=255, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the bank', max_length=50, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Email address of the bank', max_length=254, null=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, help_text='Optional description about the bank', null=True, verbose_name='Description')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', related_query_name='%(app_label)s_%(class)s', to='core.farm', verbose_name='Farm')),
                ('main_currency', models.ForeignKey(help_text='Main currency used by the bank', on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='farm_settings.currency', verbose_name='Main Currency')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
    ]
