# Generated by Django 5.1.7 on 2025-07-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('core', '0009_alter_invitetoken_farm_alter_person_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(help_text='Unique identifier for the loan', max_length=100, unique=True, verbose_name='Loan Number')),
                ('loan_name', models.CharField(help_text='Name or title of the loan', max_length=255, verbose_name='Loan Name')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the loan', max_digits=14, verbose_name='Loan Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate of the loan in percentage', max_digits=5, verbose_name='Interest Rate (%)')),
                ('loan_duration', models.PositiveIntegerField(help_text='Duration of the loan in months', verbose_name='Loan Duration (months)')),
                ('start_date', models.DateField(help_text='Date when the loan starts', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Date when the loan is due', verbose_name='End Date')),
                ('repayment_method', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('bullet', 'Bullet Payment'), ('custom', 'Custom')], default='monthly', help_text='Method of repayment for this loan', max_length=20, verbose_name='Repayment Method')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted')], default='active', help_text='Current status of the loan', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Optional description for the loan', null=True, verbose_name='Description')),
                ('bank', models.ForeignKey(help_text='Bank providing the loan', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='banking.bank', verbose_name='Bank')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', related_query_name='%(app_label)s_%(class)s', to='core.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-start_date'],
            },
        ),
    ]
