# Generated by Django 5.1.7 on 2025-07-10 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bank_created_at_bank_updated_at_loan_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
