# Generated by Django 5.1.7 on 2025-07-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_loanpayment_created_at_loanpayment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('payed', 'Payed')], default='confirmed', help_text='Status of the payment', max_length=20, verbose_name='Status'),
        ),
    ]
