# Generated by Django 5.1.7 on 2025-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_loanpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='confirmed', help_text='Status of the payment', max_length=20, verbose_name='Status'),
        ),
    ]
