# Generated by Django 5.1.7 on 2025-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalvaccine',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('expired', 'Expired'), ('valid', 'Valid'), ('missed', 'Missed')], default='given', help_text='Current status of the vaccination.', max_length=20, verbose_name='Status'),
        ),
    ]
