# Generated by Django 5.1.7 on 2025-05-31 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_animalvaccine_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBirthVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the recommended vaccine.', max_length=200, verbose_name='Vaccine Name')),
                ('date_given', models.DateField(help_text='Date the vaccine is recommended to be given.', verbose_name='Scheduled Date')),
                ('valid_until', models.DateField(help_text='How long the vaccine remains valid.', verbose_name='Valid Until')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('expired', 'Expired'), ('valid', 'Valid'), ('missed', 'Missed')], default='scheduled', help_text='Current status of the vaccine.', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Optional notes.', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Optional image proof.', null=True, upload_to='animal/birth_vaccines/', verbose_name='Image')),
                ('birth', models.ForeignKey(help_text='Birth entry this vaccine is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='planned_vaccines', to='animal.animalbirth', verbose_name='Animal Birth')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Planned Vaccine for Birth',
                'verbose_name_plural': 'Planned Vaccines for Birth',
                'unique_together': {('birth', 'name', 'date_given')},
            },
        ),
    ]
