# Generated by Django 5.1.7 on 2025-05-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_animalbirthvaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalvaccine',
            name='applies_to_purchased',
            field=models.BooleanField(blank=True, default=False, help_text='True if Animal is from external farm.', null=True, verbose_name='Image'),
        ),
    ]
