# Generated by Django 5.1.7 on 2025-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_animalvaccine_applies_to_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalvaccine',
            name='applies_to_purchased',
            field=models.BooleanField(blank=True, default=False, help_text='If true, this vaccine is recommended for animals added from outside the farm.', null=True, verbose_name='Applies to Purchased Animals'),
        ),
    ]
