# Generated by Django 5.1.7 on 2025-04-04 01:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('international_number', models.CharField(max_length=100, unique=True, verbose_name='International Number')),
                ('land_number', models.CharField(db_index=True, max_length=100, verbose_name='Land Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (USD)')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchase Date')),
                ('land_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=50, verbose_name='Land Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (sqm)')),
                ('circumference', models.CharField(max_length=50, verbose_name="Earth's circumference")),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('cultivation', 'Under Cultivation'), ('sold', 'Sold'), ('other', 'Other')], default='available', max_length=20, verbose_name='Land Status')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude in decimal degrees.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude in decimal degrees.', max_digits=9, null=True, verbose_name='Longitude')),
                ('google_maps_url', models.URLField(blank=True, help_text='Direct URL to the land on Google Maps.', max_length=500, null=True, verbose_name='Google Maps URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lands', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.farm', verbose_name='Farm')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previously_owned_lands', to=settings.AUTH_USER_MODEL, verbose_name='Previous Owner')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Lands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='land/documents/', verbose_name='Document')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='land.land', verbose_name='Land')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='land/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='land.land', verbose_name='Land')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], default='purchase', max_length=20, verbose_name='Transaction Type')),
                ('seller_name', models.CharField(default='Farm Seller', max_length=255, verbose_name='Seller Name')),
                ('seller_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller Contact')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (USD)')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='land.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Land Transaction',
                'verbose_name_plural': 'Land Transactions',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Wilaya Name')),
                ('code', models.CharField(default='TR', max_length=20, verbose_name='Wilaya Code')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='land',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='land.wilaya', verbose_name='Wilaya'),
        ),
        migrations.AddIndex(
            model_name='wilaya',
            index=models.Index(fields=['name'], name='land_wilaya_name_725f76_idx'),
        ),
        migrations.AddIndex(
            model_name='wilaya',
            index=models.Index(fields=['code'], name='land_wilaya_code_c950de_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['international_number'], name='land_land_interna_8b50e4_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['land_number'], name='land_land_land_nu_b19138_idx'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=models.Index(fields=['wilaya'], name='land_land_wilaya__355473_idx'),
        ),
    ]
