# Generated by Django 5.1.7 on 2025-06-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0004_make_farms_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
