# Generated by Django 5.1.7 on 2025-06-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0005_rename_supplier_id_asset_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets_projects.project', verbose_name='Project'),
        ),
    ]
