# Generated by Django 5.1.7 on 2025-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0006_asset_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark whether the project is currently active or not.', verbose_name='Is Active'),
        ),
    ]
