# Generated by Django 5.1.7 on 2025-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0010_alter_project_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True, verbose_name='Asset Code'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Asset Number'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_code',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True, verbose_name='Cost Code'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='cost_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Cost Number'),
        ),
    ]
