# Generated by Django 5.1.7 on 2025-07-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0011_asset_asset_code_asset_asset_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True, verbose_name='Asset Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='cost_code',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True, verbose_name='Cost Code'),
            preserve_default=False,
        ),
    ]
