# Generated by Django 5.1.7 on 2025-07-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0012_alter_asset_asset_code_alter_projectcost_cost_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
