# Generated by Django 5.1.7 on 2025-07-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0013_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when the project is planned to end', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when the project is planned to start', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total Costs'),
        ),
    ]
