# Generated by Django 5.1.7 on 2025-07-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_projects', '0014_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='project',
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_project',
            field=models.ForeignKey(blank=True, help_text='Main project this asset is linked to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assets', to='assets_projects.project', verbose_name='Primary Project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='shared_projects',
            field=models.ManyToManyField(blank=True, help_text='Other projects this asset is used in.', related_name='shared_assets', to='assets_projects.project', verbose_name='Shared Projects'),
        ),
    ]
